version: '3.8'

services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
      - 443:443
    volumes:
      # Mount the host's localtime socket into the container
      - '/etc/localtime:/etc/localtime:ro'
      # Mount the host's Docker socket into the container
      - '/var/run/docker.sock:/var/run/docker.sock'
      # Mount the host's data directory into the container
      - /portainer_data:/data
      # # Mount the host's certificate directory into the container
      # - /letsencrypt:/etc/letsencrypt

    # security_opt:
    #   - no-new-privileges:true

volumes:
  portainer_data:
  # letsencrypt:
