version: '3.8'

services:
  portainer-agent:
    image: 'portainer/agent:latest'
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - '9001:9001'
    
    
    volumes:
      # Mount the host's localtime socket into the container
      - '/etc/localtime:/etc/localtime:ro'
      # Mount the host's Docker socket into the container
      - '/var/run/docker.sock:/var/run/docker.sock'
      # Mount the host's Docker volumes into the container # Ubuntu Dir
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    pull_policy: always
    

  # healthcheck:
  #   test: ["CMD", "/bin/check-health"]
  #   interval: 10s
  #   timeout: 3s
