version: "3.8"

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager 
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      # Mount the host's localtime socket into the container
      - '/etc/localtime:/etc/localtime:ro'
      # Mount the host's Docker socket into the container
      - '/var/run/docker.sock:/var/run/docker.sock'
      # Mount the host's data directory into the container
      - npm-data:/data
      # Mount the host's certificate directory into the container
      - letsencrypt:/etc/letsencrypt

#     networks:
#       - npm-network

# networks:
#   npm-network:
#     external: true

volumes:
  npm-data:
  letsencrypt: